name: gamemaster_hub
description: Multi-platform game management hub for Soccer Manager, Football Manager, and Star Wars Galaxy of Heroes.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  
  # Navigation
  go_router: ^12.1.1
  
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  flutter_dotenv: ^6.0.0
  
  # Network & API
  dio: ^5.3.2
  
  # Authentication
  supabase_flutter: ^1.10.25
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  multi_select_flutter: ^4.1.3
  
  # Utilities
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  intl: ^0.18.1
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  
  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
  #   - assets/images/
  #   - assets/icons/
      - assets/.env
  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/static/Orbitron-Regular.ttf
        - asset: assets/fonts/static/Orbitron-Bold.ttf
          weight: 700
        - asset: assets/fonts/static/Orbitron-Black.ttf
          weight: 900